name: CI - Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ci:
    name: PR Continuous Integration
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Publish Package
        uses: UseKeyp/publish-pr-packages@v1.0.2
        with:
          # REQUIRED - Github Personal Access Token or Npm Auth Token 
          token: ${{ secrets.PAT }}
          # Command to build run for each package
          build-command: "yarn pre-publish"
          # Relative path to your package(s)
          packages-directory: packages
          # Which registry to use: github, npm
          registry: github 
          # Name which will appear in the installation instruction
          package-name: "@usekeyp/ui-kit"
