name: Deploy Component Library

on:
  push:
    branches: [main, staging]
  workflow_dispatch:

jobs:
  deploy:
    name: Styleguidist Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install packages
        working-directory: ./packages/ui-kit
        run: npm install
      - name: Generate CSS Output
        working-directory: ./packages/ui-kit
        run: npx tailwindcss -i ./src/index.css -o ./dist/output.css
      - name: Build the app w/styleguidist
        working-directory: ./packages/ui-kit
        run: ../../node_modules/.bin/styleguidist build --config styleguide.config.cjs
      - name: Install Surge
        working-directory: ./packages/ui-kit
        run: npm install -g surge
      - name: Get Deployment URL
        id: get_deployment_url
        run: |
          DEPLOYMENT_URL=https://ui.staging-env.usekeyp.com
          if ${{ github.ref_name }} == 'main' ; then
            DEPLOYMENT_URL=https://ui.usekeyp.com
          fi
          echo DEPLOYMENT_URL: $DEPLOYMENT_URL
          echo "::set-output name=DEPLOYMENT_URL::$DEPLOYMENT_URL"
      - name: Deploy to surge
        working-directory: ./packages/ui-kit
        run: surge ./styleguide ${{steps.get_deployment_url.outputs.DEPLOYMENT_URL}} --token ${{secrets.TOKEN}}
      - name: Discord notify
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_RELEASE }}
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        with:
          args: 🚢 Shipped! `${{ github.repository }}` New surge deployment ${{steps.get_deployment_url.outputs.DEPLOYMENT_URL}}
